### ISSUE TITLE
Publish opensim-core on PyPI

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3939]
Hi, I think opensim-core can be published on PyPI with minimal effort, for those who have to work with official Python and pip. 

Here, I created a workflow in GitHub Actions (derived from yours) that clones opensim-core, builds it for Windows (Python 3.12), creates a wheel file, and uploads it (available in artifacts):
https://github.com/mrrezaie/testBuildOpenSim/blob/main/.github/workflows/main.yml#L100-L102

The wheel file can be installed easily using `pip install zzz.whl`, or be published on PyPI for any Python users: https://medium.com/@blackary/publishing-a-python-package-from-github-to-pypi-in-2024-a6fb8635d45d

Also, installing the PyPI package in Google Colab would be much faster than the conda package (through condacolab).

Hope this helps.

**Comment by alexbeattie42** [comment]
[This issue](https://github.com/opensim-org/opensim-core/issues/3568) seems relevant to the discussion also.

**Comment by mrrezaie** [comment]
Hi @aymanhab 

It's great to see OpenSim is going to be available on PyPI, I appreciate that. I was wondering if it would be possible to support multiple Python versions. This can be done with minimal effort through [matrix strategy](https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations).  I did this for my personal use: 
https://github.com/mrrezaie/testBuildOpenSim/blob/main/.github/workflows/build_opensim-jam.yml#L18

```
        strategy:
            matrix:
                # os: [windows-2022]
                include:

                  - label: 'py313'
                    python_version: '3.13.*'
                    numpy_version: '2.*'

                  - label: 'py314'
                    python_version: '3.14.*'
                    numpy_version: '2.*'
```

```
- name: Install Python ${{ matrix.python_version }}
  uses: actions/setup-python@v4
  with:
      python-version: ${{ matrix.python_version }}


- name: Install NumPy 
  run: |
      python -m pip install --upgrade pip
      python -m pip install numpy==${{ matrix.numpy_version }} setuptools wheel


...


- name: Upload GUI installer
  uses: actions/upload-artifact@v4
  with:
      name: openism-gui-win64-${{ matrix.label }}-${{ env.date }}
      path: ~/opensim-gui/Gui/opensim/dist/installer/opensim
```

Thank you in advance.
